export const MQTT_MODULE_OPTIONS_CONSTANT = 'MQTT_MODULE_OPTIONS_CONSTANT';
export const MQTT_CLIENT_MODULE_OPTIONS_CONSTANT = 'MQTT_CLIENT_MODULE_OPTIONS_CONSTANT';
export const MQTT_BROKER_MODULE_OPTIONS_CONSTANT = 'MQTT_BROKER_MODULE_OPTIONS_CONSTANT';

export const MQTT_BROKER_CONSTANT = 'MQTT_BROKER_CONSTANT';
export const MQTT_CLIENT_CONSTANT = 'MQTT_CLIENT_CONSTANT';

export const MQTT_SUBSCRIBER_PARAMS_CONSTANT = 'MQTT_SUBSCRIBER_PARAMS_CONSTANT';
export const MQTT_LISTENER_METADATA_CONSTANT = 'MQTT_LISTENER_METADATA_CONSTANT';

export const MQTT_BROKER_HOOKS_METADATA_CONSTANT = 'MQTT_BROKER_HOOKS_METADATA_CONSTANT';
export const MQTT_BROKER_EVENTS_METADATA_CONSTANT = 'MQTT_BROKER_EVENTS_METADATA_CONSTANT';
