export const RMQ_PARAM_METADATA = 'RMQ_PARAM_METADATA';
export const RMQ_CONSUMER_METADATA = 'RMQ_CONSUMER_METADATA';
export const RMQ_PUBLISHER_SERVICE = 'RMQ_PUBLISHER_SERVICE';
export const RMQ_CONSUMER_SERVICE = 'RMQ_CONSUMER_SERVICE';
